dog_services = [
    {
        "code": "DOG_01",  
        "name": "dog_walk_park",
        "demand": 66,
        "accessibility": [30, 45],
        "land_use": ["recreation"],
        "bricks": [
            {"capacity": 5, "area": 100, "is_integrated": False, "parking_area": 0},
            {"capacity": 10, "area": 200, "is_integrated": False, "parking_area": 0},
            {"capacity": 15, "area": 300, "is_integrated": False, "parking_area": 0},
            {"capacity": 20, "area": 400, "is_integrated": False, "parking_area": 0},
            {"capacity": 25, "area": 500, "is_integrated": False, "parking_area": 0},
            {"capacity": 30, "area": 600, "is_integrated": False, "parking_area": 0},
            {"capacity": 35, "area": 700, "is_integrated": False, "parking_area": 0},
            {"capacity": 40, "area": 800, "is_integrated": False, "parking_area": 0},
            {"capacity": 45, "area": 900, "is_integrated": False, "parking_area": 0},
            {"capacity": 50, "area": 1000, "is_integrated": False, "parking_area": 0},
        ],
    },
    {
        "code": "DOG_02",  
        "name": "dog_train_park",
        "demand": 66,
        "accessibility": 45,
        "land_use": ["recreation"],
        "bricks": [
            {"capacity": 5, "area": 100, "is_integrated": False, "parking_area": 0},
            {"capacity": 10, "area": 200, "is_integrated": False, "parking_area": 0},
            {"capacity": 15, "area": 300, "is_integrated": False, "parking_area": 0},
            {"capacity": 20, "area": 400, "is_integrated": False, "parking_area": 0},
            {"capacity": 25, "area": 500, "is_integrated": False, "parking_area": 0},
            {"capacity": 30, "area": 600, "is_integrated": False, "parking_area": 0},
            {"capacity": 35, "area": 700, "is_integrated": False, "parking_area": 0},
            {"capacity": 40, "area": 800, "is_integrated": False, "parking_area": 0},
            {"capacity": 45, "area": 900, "is_integrated": False, "parking_area": 0},
            {"capacity": 50, "area": 1000, "is_integrated": False, "parking_area": 0},
        ],
    },
    {
        "code": "DOG_03",  
        "name": "small_park",
        "demand": 66,
        "accessibility": [15, 30, 45],
        "land_use": ["recreation"],
        "bricks": [
            {"capacity": 833, "area": 25000, "is_integrated": False, "parking_area": 0},
            {"capacity": 1667, "area": 50000, "is_integrated": False, "parking_area": 0},
            {"capacity": 2500, "area": 75000, "is_integrated": False, "parking_area": 0},
            {"capacity": 3333, "area": 100000, "is_integrated": False, "parking_area": 0},
            {"capacity": 4167, "area": 125000, "is_integrated": False, "parking_area": 0},
            {"capacity": 5000, "area": 150000, "is_integrated": False, "parking_area": 0},
            {"capacity": 5833, "area": 175000, "is_integrated": False, "parking_area": 0},
            {"capacity": 6667, "area": 200000, "is_integrated": False, "parking_area": 0},
            {"capacity": 7500, "area": 225000, "is_integrated": False, "parking_area": 0},
            {"capacity": 8333, "area": 250000, "is_integrated": False, "parking_area": 0},
            {"capacity": 9167, "area": 275000, "is_integrated": False, "parking_area": 0},
            {"capacity": 10000, "area": 300000, "is_integrated": False, "parking_area": 0},
        ],
    },
    {
        "code": "DOG_04",  
        "name": "large_park",
        "demand": 66,
        "accessibility": [30, 45],
        "land_use": ["recreation"],
        "bricks": [
            {"capacity": 11429, "area": 400000, "is_integrated": False, "parking_area": 0},
            {"capacity": 14286, "area": 500000, "is_integrated": False, "parking_area": 0},
            {"capacity": 17143, "area": 600000, "is_integrated": False, "parking_area": 0},
            {"capacity": 20000, "area": 700000, "is_integrated": False, "parking_area": 0},
            {"capacity": 22857, "area": 800000, "is_integrated": False, "parking_area": 0},
            {"capacity": 25714, "area": 900000, "is_integrated": False, "parking_area": 0},
            {"capacity": 28571, "area": 1000000, "is_integrated": False, "parking_area": 0},
            {"capacity": 31429, "area": 1100000, "is_integrated": False, "parking_area": 0},
            {"capacity": 34286, "area": 1200000, "is_integrated": False, "parking_area": 0},
            {"capacity": 37143, "area": 1300000, "is_integrated": False, "parking_area": 0},
            {"capacity": 40000, "area": 1400000, "is_integrated": False, "parking_area": 0},
            {"capacity": 42857, "area": 1500000, "is_integrated": False, "parking_area": 0},
            {"capacity": 45714, "area": 1600000, "is_integrated": False, "parking_area": 0},
            {"capacity": 48571, "area": 1700000, "is_integrated": False, "parking_area": 0},
            {"capacity": 51429, "area": 1800000, "is_integrated": False, "parking_area": 0},
            {"capacity": 54286, "area": 1900000, "is_integrated": False, "parking_area": 0},
            {"capacity": 57143, "area": 2000000, "is_integrated": False, "parking_area": 0},
            {"capacity": 60000, "area": 2100000, "is_integrated": False, "parking_area": 0},
            {"capacity": 62857, "area": 2200000, "is_integrated": False, "parking_area": 0},
            {"capacity": 65714, "area": 2300000, "is_integrated": False, "parking_area": 0},
            {"capacity": 68571, "area": 2400000, "is_integrated": False, "parking_area": 0},
            {"capacity": 71429, "area": 2500000, "is_integrated": False, "parking_area": 0},
            {"capacity": 74286, "area": 2600000, "is_integrated": False, "parking_area": 0},
            {"capacity": 77143, "area": 2700000, "is_integrated": False, "parking_area": 0},
            {"capacity": 80000, "area": 2800000, "is_integrated": False, "parking_area": 0},
            {"capacity": 82857, "area": 2900000, "is_integrated": False, "parking_area": 0},
            {"capacity": 85714, "area": 3000000, "is_integrated": False, "parking_area": 0}
        ],
    },
    {
        "code": "DOG_05",
        "name": "petshop",
        "demand": 66,
        "accessibility": [15, 30, 45],
        "land_use": ["residential", "business"],
        "bricks": [
            {"capacity": 5, "area": 15, "is_integrated": True, "parking_area": 0},
            {"capacity": 10, "area": 30, "is_integrated": True, "parking_area": 0},
            {"capacity": 15, "area": 45, "is_integrated": True, "parking_area": 0},
            {"capacity": 20, "area": 60, "is_integrated": True, "parking_area": 0},
            {"capacity": 25, "area": 75, "is_integrated": True, "parking_area": 0},
            {"capacity": 30, "area": 90, "is_integrated": True, "parking_area": 0},
            {"capacity": 35, "area": 105, "is_integrated": True, "parking_area": 0},
            {"capacity": 40, "area": 120, "is_integrated": True, "parking_area": 0},
            {"capacity": 45, "area": 135, "is_integrated": True, "parking_area": 0},
            {"capacity": 50, "area": 150, "is_integrated": True, "parking_area": 0}
        ]
    },
    {
        "code": "DOG_06",
        "name": "veterinary",
        "demand": 66,
        "accessibility": [30, 45],
        "land_use": ["residential", "business"],
        "bricks": [
            {"capacity": 5, "area": 30, "is_integrated": True, "parking_area": 0},
            {"capacity": 8, "area": 50, "is_integrated": True, "parking_area": 0},
            {"capacity": 10, "area": 65, "is_integrated": True, "parking_area": 0},
            {"capacity": 12, "area": 75, "is_integrated": True, "parking_area": 0},
            {"capacity": 15, "area": 90, "is_integrated": True, "parking_area": 0},
            {"capacity": 18, "area": 105, "is_integrated": True, "parking_area": 0},
            {"capacity": 22, "area": 125, "is_integrated": True, "parking_area": 0},
            {"capacity": 25, "area": 140, "is_integrated": True, "parking_area": 0},
            {"capacity": 28, "area": 160, "is_integrated": True, "parking_area": 0},
            {"capacity": 30, "area": 180, "is_integrated": True, "parking_area": 0}
        ]
    }
    ]